# .github/workflows/convert-markdown-to-docx.yml
name: Convert Markdown to DOCX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install python-docx

      - name: Run conversion script
        run: |
          python scripts/convert_md_to_docx.py

      - name: Commit and push DOCX files to `doc` branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # switch to (or create) the doc branch
          if git rev-parse --verify doc; then
            git checkout doc
          else
            git checkout -b doc
          fi
          # stage and commit
          git add report/*.docx
          git commit -m "Auto-convert MD→DOCX on $(date +'%Y-%m-%d')" || echo "No changes to commit"
          # push back to origin/doc
          git push --force --set-upstream origin doc

