# .github/workflows/convert-markdown-to-docx.yml
name: Convert Markdown to DOCX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install python-docx

      - name: Run conversion script
        run: |
          python scripts/convert_md_to_docx.py

      - name: Commit and push DOCX files back to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # stage new/updated DOCX
          git add report/*.docx
          # commit with skip-ci to avoid infinite loop
          git commit -m "Auto-convert MD→DOCX on $(date +'%Y-%m-%d') [skip ci]" || echo "No changes to commit"
          # push back to main
          git push origin HEAD:main
